In [0]:
%load_ext autoreload
%autoreload 2
# Enables autoreload; learn more at https://docs.databricks.com/en/files/workspace-modules.html#autoreload-for-python-modules
# To disable autoreload; run %autoreload 0

In [0]:
%reload_ext autoreload

In [0]:
import sys

# Add project root to sys.path so 'src' becomes importable
project_path = "/Workspace/Users/krishnasumanbhaipatel@gmail.com/Practice Folder/lakehouse-practice-project"
if project_path not in sys.path:
    sys.path.insert(0, project_path)

In [0]:
# Import the modules
from src.ingestion.bronze import ingest_table
from src.metadata.bronze_pipeline_metadata import TABLE_METADATA 
from src.orchestration.batch import get_batch_id
from src.utils.config import CATALOG, AUDIT_SCHEMA, AUDIT_TABLENAME
from pyspark.sql import SparkSession

# Get Spark session
spark = SparkSession.builder.getOrCreate()

# Process each table with its own sequential batch_id
for table, metadata in TABLE_METADATA.items():
    # Get next sequential batch ID for this table
    BATCH_ID = get_batch_id(spark, CATALOG, AUDIT_SCHEMA, AUDIT_TABLENAME)
    print(f"Processing {metadata['target']} with batch_id: {BATCH_ID}")
    
    ingest_table(
        source=metadata["source"],
        target=metadata["target"],
        pipeline_name="bronze_ingestion_pipeline",
        primary_key=metadata["primary_key"], 
        bronze_watermark_column=metadata["watermark_column"],
        batch_id=BATCH_ID
    )

Processing customers with batch_id: 15
2026-08-14 08:22:51,684 | INFO     | bronze.customers | Logging to file: /Workspace/Users/krishnasumanbhaipatel@gmail.com/Practice Folder/lakehouse-practice-project/logs/bronze_customers_20260814.log
2026-08-14 08:22:51,686 | INFO     | bronze.customers | Checking for last successful run
2026-08-14 08:22:52,476 | INFO     | bronze.customers | Fetched watermark value: 2025-02-16 00:00:00
2026-08-14 08:22:52,479 | INFO     | bronze.customers | Reading source customers_raw table
2026-08-14 08:22:52,508 | INFO     | bronze.customers | Starting pre-write validations
Source table is empty
2026-08-14 08:22:53,749 | INFO     | bronze.customers | Rows read from source: 0
root
 |-- customer_id: integer (nullable = false)
 |-- name: string (nullable = false)
 |-- email: string (nullable = false)
 |-- city: string (nullable = true)
 |-- state: string (nullable = true)
 |-- signup_date: timestamp (nullable = true)
 |-- created_date: timestamp (nullable = true)
 |-- modified_date: timestamp (nullable = true)

2026-08-14 08:22:53,954 | INFO     | bronze.customers | Pre-write validations passed. Source customers_raw ready for ingestion.
2026-08-14 08:22:53,955 | INFO     | bronze.customers | Starting Bronze customers ingestion
2026-08-14 08:22:53,956 | INFO     | bronze.customers | Source table: customers_raw
2026-08-14 08:22:53,957 | INFO     | bronze.customers | Target table: customers
2026-08-14 08:22:55,470 | INFO     | bronze.customers | Bronze customers table written successfully.
2026-08-14 08:22:55,472 | INFO     | bronze.customers | Starting post-write validations
2026-08-14 08:22:55,892 | INFO     | bronze.customers | No new data found. Using previous watermark: 2025-02-16 00:00:00
2026-08-14 08:22:55,897 | INFO     | bronze.customers | Rows written in this run: 0
2026-08-14 08:22:56,486 | INFO     | bronze.customers | Total rows in bronze table: 98
2026-08-14 08:22:57,330 | WARNING  | bronze.customers | ⚠️ PRIMARY KEY duplicates found: 15 groups
2026-08-14 08:22:58,239 | WARNING  | bronze.customers | ⚠️ Full row duplicates found: 15 groups
2026-08-14 08:22:58,619 | INFO     | bronze.customers | No NULL values found
root
 |-- customer_id: integer (nullable = true)
 |-- name: string (nullable = true)
 |-- email: string (nullable = true)
 |-- city: string (nullable = true)
 |-- state: string (nullable = true)
 |-- signup_date: timestamp (nullable = true)
 |-- created_date: timestamp (nullable = true)
 |-- modified_date: timestamp (nullable = true)
 |-- _ingestion_timestamp: timestamp (nullable = true)
 |-- _source_file: string (nullable = true)
 |-- _source_table: string (nullable = true)
 |-- _ingestion_job_id: string (nullable = true)
 |-- _ingestion_pipeline_id: string (nullable = true)

2026-08-14 08:22:58,622 | INFO     | bronze.customers | Post-write validations completed. Bronze customers ingestion finished successfully.
2026-08-14 08:23:00,563 | INFO     | bronze.customers | Audit log written successfully
Processing products with batch_id: 16
2026-08-14 08:23:01,236 | INFO     | bronze.products | Logging to file: /Workspace/Users/krishnasumanbhaipatel@gmail.com/Practice Folder/lakehouse-practice-project/logs/bronze_products_20260814.log
2026-08-14 08:23:01,239 | INFO     | bronze.products | Checking for last successful run
2026-08-14 08:23:02,018 | INFO     | bronze.products | Fetched watermark value: 2024-12-17 00:00:00
2026-08-14 08:23:02,019 | INFO     | bronze.products | Reading source products_raw table
2026-08-14 08:23:02,049 | INFO     | bronze.products | Starting pre-write validations
Source table is empty
2026-08-14 08:23:03,291 | INFO     | bronze.products | Rows read from source: 0
root
 |-- product_id: integer (nullable = false)
 |-- product_name: string (nullable = true)
 |-- category: string (nullable = true)
 |-- brand: string (nullable = true)
 |-- price: integer (nullable = true)
 |-- created_date: timestamp (nullable = true)
 |-- modified_date: timestamp (nullable = true)

2026-08-14 08:23:03,569 | INFO     | bronze.products | Pre-write validations passed. Source products_raw ready for ingestion.
2026-08-14 08:23:03,570 | INFO     | bronze.products | Starting Bronze products ingestion
2026-08-14 08:23:03,571 | INFO     | bronze.products | Source table: products_raw
2026-08-14 08:23:03,573 | INFO     | bronze.products | Target table: products
2026-08-14 08:23:05,046 | INFO     | bronze.products | Bronze products table written successfully.
2026-08-14 08:23:05,047 | INFO     | bronze.products | Starting post-write validations
2026-08-14 08:23:05,558 | INFO     | bronze.products | No new data found. Using previous watermark: 2024-12-17 00:00:00
2026-08-14 08:23:05,559 | INFO     | bronze.products | Rows written in this run: 0
2026-08-14 08:23:06,120 | INFO     | bronze.products | Total rows in bronze table: 32
2026-08-14 08:23:06,790 | WARNING  | bronze.products | ⚠️ PRIMARY KEY duplicates found: 6 groups
2026-08-14 08:23:07,373 | INFO     | bronze.products | No full row duplicates found
2026-08-14 08:23:08,605 | INFO     | bronze.products | No NULL values found
root
 |-- product_id: integer (nullable = true)
 |-- product_name: string (nullable = true)
 |-- category: string (nullable = true)
 |-- brand: string (nullable = true)
 |-- price: integer (nullable = true)
 |-- created_date: timestamp (nullable = true)
 |-- modified_date: timestamp (nullable = true)
 |-- _ingestion_timestamp: timestamp (nullable = true)
 |-- _source_file: string (nullable = true)
 |-- _source_table: string (nullable = true)
 |-- _ingestion_job_id: string (nullable = true)
 |-- _ingestion_pipeline_id: string (nullable = true)

2026-08-14 08:23:08,607 | INFO     | bronze.products | Post-write validations completed. Bronze products ingestion finished successfully.
2026-08-14 08:23:10,231 | INFO     | bronze.products | Audit log written successfully
Processing orders with batch_id: 17
2026-08-14 08:23:11,142 | INFO     | bronze.orders | Logging to file: /Workspace/Users/krishnasumanbhaipatel@gmail.com/Practice Folder/lakehouse-practice-project/logs/bronze_orders_20260814.log
2026-08-14 08:23:11,143 | INFO     | bronze.orders | Checking for last successful run
2026-08-14 08:23:11,983 | INFO     | bronze.orders | Fetched watermark value: 2025-03-28 00:00:00
2026-08-14 08:23:11,986 | INFO     | bronze.orders | Reading source orders_raw table
2026-08-14 08:23:12,026 | INFO     | bronze.orders | Starting pre-write validations
Source table is empty
2026-08-14 08:23:13,075 | INFO     | bronze.orders | Rows read from source: 0
root
 |-- order_id: integer (nullable = false)
 |-- customer_id: integer (nullable = true)
 |-- order_date: timestamp (nullable = true)
 |-- status: string (nullable = true)
 |-- created_date: timestamp (nullable = true)
 |-- modified_date: timestamp (nullable = true)

2026-08-14 08:23:13,253 | INFO     | bronze.orders | Pre-write validations passed. Source orders_raw ready for ingestion.
2026-08-14 08:23:13,254 | INFO     | bronze.orders | Starting Bronze orders ingestion
2026-08-14 08:23:13,256 | INFO     | bronze.orders | Source table: orders_raw
2026-08-14 08:23:13,257 | INFO     | bronze.orders | Target table: orders
2026-08-14 08:23:15,140 | INFO     | bronze.orders | Bronze orders table written successfully.
2026-08-14 08:23:15,142 | INFO     | bronze.orders | Starting post-write validations
2026-08-14 08:23:15,656 | INFO     | bronze.orders | No new data found. Using previous watermark: 2025-03-28 00:00:00
2026-08-14 08:23:15,657 | INFO     | bronze.orders | Rows written in this run: 0
2026-08-14 08:23:16,221 | INFO     | bronze.orders | Total rows in bronze table: 10
2026-08-14 08:23:16,618 | INFO     | bronze.orders | No primary key duplicates found
2026-08-14 08:23:17,014 | INFO     | bronze.orders | No full row duplicates found
2026-08-14 08:23:17,419 | INFO     | bronze.orders | No NULL values found
root
 |-- order_id: integer (nullable = true)
 |-- customer_id: integer (nullable = true)
 |-- order_date: timestamp (nullable = true)
 |-- status: string (nullable = true)
 |-- created_date: timestamp (nullable = true)
 |-- modified_date: timestamp (nullable = true)
 |-- _ingestion_timestamp: timestamp (nullable = true)
 |-- _source_file: string (nullable = true)
 |-- _source_table: string (nullable = true)
 |-- _ingestion_job_id: string (nullable = true)
 |-- _ingestion_pipeline_id: string (nullable = true)

2026-08-14 08:23:17,436 | INFO     | bronze.orders | Post-write validations completed. Bronze orders ingestion finished successfully.
2026-08-14 08:23:18,939 | INFO     | bronze.orders | Audit log written successfully
Processing payments with batch_id: 18
2026-08-14 08:23:19,676 | INFO     | bronze.payments | Logging to file: /Workspace/Users/krishnasumanbhaipatel@gmail.com/Practice Folder/lakehouse-practice-project/logs/bronze_payments_20260814.log
2026-08-14 08:23:19,677 | INFO     | bronze.payments | Checking for last successful run
2026-08-14 08:23:20,536 | INFO     | bronze.payments | Fetched watermark value: 2025-03-28 00:00:00
2026-08-14 08:23:20,537 | INFO     | bronze.payments | Reading source payments_raw table
2026-08-14 08:23:20,568 | INFO     | bronze.payments | Starting pre-write validations
Source table is empty
2026-08-14 08:23:21,997 | INFO     | bronze.payments | Rows read from source: 0
root
 |-- payment_id: integer (nullable = false)
 |-- order_id: integer (nullable = true)
 |-- payment_method: string (nullable = true)
 |-- payment_status: string (nullable = true)
 |-- amount: integer (nullable = true)
 |-- created_date: timestamp (nullable = true)
 |-- modified_date: timestamp (nullable = true)

2026-08-14 08:23:22,203 | INFO     | bronze.payments | Pre-write validations passed. Source payments_raw ready for ingestion.
2026-08-14 08:23:22,204 | INFO     | bronze.payments | Starting Bronze payments ingestion
2026-08-14 08:23:22,206 | INFO     | bronze.payments | Source table: payments_raw
2026-08-14 08:23:22,211 | INFO     | bronze.payments | Target table: payments
2026-08-14 08:23:23,612 | INFO     | bronze.payments | Bronze payments table written successfully.
2026-08-14 08:23:23,613 | INFO     | bronze.payments | Starting post-write validations
2026-08-14 08:23:24,101 | INFO     | bronze.payments | No new data found. Using previous watermark: 2025-03-28 00:00:00
2026-08-14 08:23:24,104 | INFO     | bronze.payments | Rows written in this run: 0
2026-08-14 08:23:24,625 | INFO     | bronze.payments | Total rows in bronze table: 10
2026-08-14 08:23:25,064 | INFO     | bronze.payments | No primary key duplicates found
2026-08-14 08:23:25,432 | INFO     | bronze.payments | No full row duplicates found
2026-08-14 08:23:25,820 | INFO     | bronze.payments | No NULL values found
root
 |-- payment_id: integer (nullable = true)
 |-- order_id: integer (nullable = true)
 |-- payment_method: string (nullable = true)
 |-- payment_status: string (nullable = true)
 |-- amount: integer (nullable = true)
 |-- created_date: timestamp (nullable = true)
 |-- modified_date: timestamp (nullable = true)
 |-- _ingestion_timestamp: timestamp (nullable = true)
 |-- _source_file: string (nullable = true)
 |-- _source_table: string (nullable = true)
 |-- _ingestion_job_id: string (nullable = true)
 |-- _ingestion_pipeline_id: string (nullable = true)

2026-08-14 08:23:25,822 | INFO     | bronze.payments | Post-write validations completed. Bronze payments ingestion finished successfully.
2026-08-14 08:23:27,536 | INFO     | bronze.payments | Audit log written successfully
Processing inventory with batch_id: 19
2026-08-14 08:23:28,207 | INFO     | bronze.inventory | Logging to file: /Workspace/Users/krishnasumanbhaipatel@gmail.com/Practice Folder/lakehouse-practice-project/logs/bronze_inventory_20260814.log
2026-08-14 08:23:28,208 | INFO     | bronze.inventory | Checking for last successful run
2026-08-14 08:23:29,051 | INFO     | bronze.inventory | Fetched watermark value: 2025-03-01 00:00:00
2026-08-14 08:23:29,053 | INFO     | bronze.inventory | Reading source inventory_raw table
2026-08-14 08:23:29,083 | INFO     | bronze.inventory | Starting pre-write validations
Source table is empty
2026-08-14 08:23:30,637 | INFO     | bronze.inventory | Rows read from source: 0
root
 |-- inventory_id: integer (nullable = false)
 |-- product_id: integer (nullable = true)
 |-- warehouse: string (nullable = true)
 |-- stock: integer (nullable = true)
 |-- last_updated: timestamp (nullable = true)
 |-- created_date: timestamp (nullable = true)
 |-- modified_date: timestamp (nullable = true)

2026-08-14 08:23:30,940 | INFO     | bronze.inventory | Pre-write validations passed. Source inventory_raw ready for ingestion.
2026-08-14 08:23:30,941 | INFO     | bronze.inventory | Starting Bronze inventory ingestion
2026-08-14 08:23:30,942 | INFO     | bronze.inventory | Source table: inventory_raw
2026-08-14 08:23:30,943 | INFO     | bronze.inventory | Target table: inventory
2026-08-14 08:23:32,474 | INFO     | bronze.inventory | Bronze inventory table written successfully.
2026-08-14 08:23:32,476 | INFO     | bronze.inventory | Starting post-write validations
2026-08-14 08:23:32,925 | INFO     | bronze.inventory | No new data found. Using previous watermark: 2025-03-01 00:00:00
2026-08-14 08:23:32,927 | INFO     | bronze.inventory | Rows written in this run: 0
2026-08-14 08:23:33,442 | INFO     | bronze.inventory | Total rows in bronze table: 10
2026-08-14 08:23:33,830 | INFO     | bronze.inventory | No primary key duplicates found
2026-08-14 08:23:34,240 | INFO     | bronze.inventory | No full row duplicates found
2026-08-14 08:23:34,665 | INFO     | bronze.inventory | No NULL values found
root
 |-- inventory_id: integer (nullable = true)
 |-- product_id: integer (nullable = true)
 |-- warehouse: string (nullable = true)
 |-- stock: integer (nullable = true)
 |-- last_updated: timestamp (nullable = true)
 |-- created_date: timestamp (nullable = true)
 |-- modified_date: timestamp (nullable = true)
 |-- _ingestion_timestamp: timestamp (nullable = true)
 |-- _source_file: string (nullable = true)
 |-- _source_table: string (nullable = true)
 |-- _ingestion_job_id: string (nullable = true)
 |-- _ingestion_pipeline_id: string (nullable = true)

2026-08-14 08:23:34,666 | INFO     | bronze.inventory | Post-write validations completed. Bronze inventory ingestion finished successfully.
2026-08-14 08:23:36,140 | INFO     | bronze.inventory | Audit log written successfully
Processing order_items with batch_id: 20
2026-08-14 08:23:36,901 | INFO     | bronze.order_items | Logging to file: /Workspace/Users/krishnasumanbhaipatel@gmail.com/Practice Folder/lakehouse-practice-project/logs/bronze_order_items_20260814.log
2026-08-14 08:23:36,902 | INFO     | bronze.order_items | Checking for last successful run
2026-08-14 08:23:37,557 | INFO     | bronze.order_items | Fetched watermark value: 2025-03-05 00:00:00
2026-08-14 08:23:37,559 | INFO     | bronze.order_items | Reading source order_items_raw table
2026-08-14 08:23:37,591 | INFO     | bronze.order_items | Starting pre-write validations
Source table is empty
2026-08-14 08:23:38,585 | INFO     | bronze.order_items | Rows read from source: 0
root
 |-- order_item_id: integer (nullable = false)
 |-- order_id: integer (nullable = true)
 |-- product_id: integer (nullable = true)
 |-- quantity: integer (nullable = true)
 |-- unit_price: integer (nullable = true)
 |-- created_date: timestamp (nullable = true)
 |-- modified_date: timestamp (nullable = true)

2026-08-14 08:23:38,763 | INFO     | bronze.order_items | Pre-write validations passed. Source order_items_raw ready for ingestion.
2026-08-14 08:23:38,765 | INFO     | bronze.order_items | Starting Bronze order_items ingestion
2026-08-14 08:23:38,767 | INFO     | bronze.order_items | Source table: order_items_raw
2026-08-14 08:23:38,768 | INFO     | bronze.order_items | Target table: order_items
2026-08-14 08:23:40,210 | INFO     | bronze.order_items | Bronze order_items table written successfully.
2026-08-14 08:23:40,210 | INFO     | bronze.order_items | Starting post-write validations
2026-08-14 08:23:40,685 | INFO     | bronze.order_items | No new data found. Using previous watermark: 2025-03-05 00:00:00
2026-08-14 08:23:40,686 | INFO     | bronze.order_items | Rows written in this run: 0
2026-08-14 08:23:41,205 | INFO     | bronze.order_items | Total rows in bronze table: 10
2026-08-14 08:23:41,599 | INFO     | bronze.order_items | No primary key duplicates found
2026-08-14 08:23:41,978 | INFO     | bronze.order_items | No full row duplicates found
2026-08-14 08:23:42,337 | INFO     | bronze.order_items | No NULL values found
root
 |-- order_item_id: integer (nullable = true)
 |-- order_id: integer (nullable = true)
 |-- product_id: integer (nullable = true)
 |-- quantity: integer (nullable = true)
 |-- unit_price: integer (nullable = true)
 |-- created_date: timestamp (nullable = true)
 |-- modified_date: timestamp (nullable = true)
 |-- _ingestion_timestamp: timestamp (nullable = true)
 |-- _source_file: string (nullable = true)
 |-- _source_table: string (nullable = true)
 |-- _ingestion_job_id: string (nullable = true)
 |-- _ingestion_pipeline_id: string (nullable = true)

2026-08-14 08:23:42,338 | INFO     | bronze.order_items | Post-write validations completed. Bronze order_items ingestion finished successfully.
2026-08-14 08:23:43,774 | INFO     | bronze.order_items | Audit log written successfully
Processing suppliers with batch_id: 21
2026-08-14 08:23:44,532 | INFO     | bronze.suppliers | Logging to file: /Workspace/Users/krishnasumanbhaipatel@gmail.com/Practice Folder/lakehouse-practice-project/logs/bronze_suppliers_20260814.log
2026-08-14 08:23:44,533 | INFO     | bronze.suppliers | Checking for last successful run
2026-08-14 08:23:45,175 | INFO     | bronze.suppliers | Fetched watermark value: 2024-12-01 00:00:00
2026-08-14 08:23:45,176 | INFO     | bronze.suppliers | Reading source suppliers_raw table
2026-08-14 08:23:45,217 | INFO     | bronze.suppliers | Starting pre-write validations
Source table is empty
2026-08-14 08:23:46,443 | INFO     | bronze.suppliers | Rows read from source: 0
root
 |-- supplier_id: integer (nullable = true)
 |-- supplier_name: string (nullable = true)
 |-- contact_name: string (nullable = true)
 |-- contact_email: string (nullable = true)
 |-- country: string (nullable = true)
 |-- city: string (nullable = true)
 |-- created_date: timestamp (nullable = true)
 |-- modified_date: timestamp (nullable = true)

2026-08-14 08:23:46,615 | INFO     | bronze.suppliers | Pre-write validations passed. Source suppliers_raw ready for ingestion.
2026-08-14 08:23:46,616 | INFO     | bronze.suppliers | Starting Bronze suppliers ingestion
2026-08-14 08:23:46,617 | INFO     | bronze.suppliers | Source table: suppliers_raw
2026-08-14 08:23:46,618 | INFO     | bronze.suppliers | Target table: suppliers
2026-08-14 08:23:48,114 | INFO     | bronze.suppliers | Bronze suppliers table written successfully.
2026-08-14 08:23:48,116 | INFO     | bronze.suppliers | Starting post-write validations
2026-08-14 08:23:48,540 | INFO     | bronze.suppliers | No new data found. Using previous watermark: 2024-12-01 00:00:00
2026-08-14 08:23:48,541 | INFO     | bronze.suppliers | Rows written in this run: 0
2026-08-14 08:23:49,036 | INFO     | bronze.suppliers | Total rows in bronze table: 12
2026-08-14 08:23:49,573 | WARNING  | bronze.suppliers | ⚠️ PRIMARY KEY duplicates found: 1 groups
2026-08-14 08:23:49,994 | INFO     | bronze.suppliers | No full row duplicates found
2026-08-14 08:23:50,541 | INFO     | bronze.suppliers | No NULL values found
root
 |-- supplier_id: integer (nullable = true)
 |-- supplier_name: string (nullable = true)
 |-- contact_name: string (nullable = true)
 |-- contact_email: string (nullable = true)
 |-- country: string (nullable = true)
 |-- city: string (nullable = true)
 |-- created_date: timestamp (nullable = true)
 |-- modified_date: timestamp (nullable = true)

In [0]:
%skip 
spark.read.table("catalog_project1.bronze.customers").toPandas()

    customer_id  ...                _ingestion_pipeline_id
0          1010  ...  ffc0eeb8-d238-433c-8030-4735daf88af8
1          1009  ...  ffc0eeb8-d238-433c-8030-4735daf88af8
2          1007  ...  ffc0eeb8-d238-433c-8030-4735daf88af8
3          1008  ...  ffc0eeb8-d238-433c-8030-4735daf88af8
4          1006  ...  ffc0eeb8-d238-433c-8030-4735daf88af8
5          1004  ...  ffc0eeb8-d238-433c-8030-4735daf88af8
6          1003  ...  ffc0eeb8-d238-433c-8030-4735daf88af8
7          1002  ...  ffc0eeb8-d238-433c-8030-4735daf88af8
8          1001  ...  ffc0eeb8-d238-433c-8030-4735daf88af8
9          1014  ...  09788b3e-4e9d-437b-89c3-7a9491598156
10         1015  ...  09788b3e-4e9d-437b-89c3-7a9491598156
11         1010  ...  f8697191-260e-4927-adbb-7fd1e399c2f9
12         1012  ...  f8697191-260e-4927-adbb-7fd1e399c2f9
13         1010  ...  204933bf-d9e8-497c-88d2-fcb00e71e443
14         1011  ...  204933bf-d9e8-497c-88d2-fcb00e71e443
15         1010  ...  21f74b2c-01f1-41d3-8b26-c886c2b21114
16         1013  ...  21f74b2c-01f1-41d3-8b26-c886c2b21114
17         1010  ...  4ba7aaf1-f548-44ab-a0f8-cca6c14866ef
18         1014  ...  4ba7aaf1-f548-44ab-a0f8-cca6c14866ef
19         1014  ...  fae4517c-4a22-4100-be86-e82505fac6d9
20         1014  ...  36eac210-12ea-4bec-9a2d-bc9c966c882c
21         1005  ...  125928f2-2b86-4017-9b55-7c146f44c3b1
22         1014  ...  78c01be5-ba63-451b-84a8-f27adb10be04

[23 rows x 13 columns]

In [0]:
spark.sql(f"SELECT * FROM catalog_project1.audit.pipeline_run_audit ORDER BY start_time DESC").toPandas()

                 pipeline_name   table_name  ... watermark_value watermark_column
0    bronze_ingestion_pipeline    suppliers  ...      2024-11-30    modified_date
1    bronze_ingestion_pipeline  order_items  ...      2025-03-05    modified_date
2    bronze_ingestion_pipeline    inventory  ...      2025-03-01    modified_date
3    bronze_ingestion_pipeline     payments  ...      2025-03-28    modified_date
4    bronze_ingestion_pipeline       orders  ...      2025-03-28    modified_date
..                         ...          ...  ...             ...              ...
615  bronze_ingestion_pipeline    inventory  ...      2025-03-01    modified_date
616  bronze_ingestion_pipeline     payments  ...      2025-03-28    modified_date
617  bronze_ingestion_pipeline       orders  ...      2025-03-28    modified_date
618  bronze_ingestion_pipeline     products  ...      2024-11-30    modified_date
619  bronze_ingestion_pipeline    customers  ...      2025-02-01    modified_date

[620 rows x 11 columns]

Note: The root cause is clear: the `src` directory exists as a workspace directory, not as a Python package directory accessible via standard Python imports on Serverless compute.

So, created setup.py in root folder to create a proper python project that can be imported anywhere. 

Install project as a python package using `%pip install -e <path>` 

Then restart the kernal using `dbutils.library.restartPython()` to use updated packages.

### How setup.py + find_packages() Works

`find_packages()` scans your project directory and finds every folder that contains an `__init__.py` file. In your case, it found:

- `src/`
- `src/ingestion/`
- `src/utils/`
- etc. 

What `%pip install -e .` does:

When you run `%pip install -e /path/to/project` (the `-e` means "editable mode"):

1. Creates a link in Python's site-packages directory pointing to your project folder
2. Registers the packages found by `find_packages()` as importable modules
3. Adds metadata so Python knows where to find these modules

After this, `import src` works from anywhere because Python knows `src` is a registered package.

The restart clears everything — the editable install doesn't persist after restartPython(). And on Serverless, without the restart, the installation doesn't fully activate.

### Approach used 
The `sys.path` approach: 

How this works:

1. `sys.path` is Python's list of directories where it searches for modules
2. By adding your project root, Python now looks there when you `import src`
3. Since `src/` has an `__init__.py`, Python treats it as a package
4. No installation needed — it's just path manipulation

### Testing

Checking if there is new data since last watermark -

In [0]:
%skip
%sql
-- Customers: watermark is 2025-02-01
SELECT 'customers' as table_name, 
       COUNT(*) as total_rows,
       COUNT(CASE WHEN modified_date > '2025-02-01' THEN 1 END) as rows_after_watermark
FROM catalog_project1.source1.customers_raw

UNION ALL

-- Products: watermark is 2024-11-30
SELECT 'products' as table_name,
       COUNT(*) as total_rows,
       COUNT(CASE WHEN modified_date > '2024-11-30' THEN 1 END) as rows_after_watermark
FROM catalog_project1.source1.products_raw

In [0]:
tables = [
    "catalog_project1.bronze.customers", 
    "catalog_project1.bronze.orders", 
    "catalog_project1.bronze.order_items", 
    "catalog_project1.bronze.products", 
    "catalog_project1.bronze.inventory", 
    "catalog_project1.bronze.payments", 
    "catalog_project1.bronze.suppliers" 
] 

for table in tables: 
    spark.sql(f"SELECT * FROM {table}").display()

customer_id,name,email,city,state,signup_date,created_date,modified_date,_ingestion_timestamp,_source_file,_source_table,_ingestion_job_id,_ingestion_pipeline_id
1010,Meera Nair,meera.nair@email.com,Kochi,Kerala,2025-02-01T00:00:00.000Z,2025-02-01T00:00:00.000Z,2025-02-07T00:00:00.000Z,2026-08-06T09:59:47.394Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/7ec5ceeb-6a38-491b-8231-055cc97e3f60/part-00000-359a242b-20cc-412e-b016-3eb8414c4741.c000.zstd.parquet,catalog_project1.source1.customers_raw,1786010386552,ffc0eeb8-d238-433c-8030-4735daf88af8
1009,Vikram Joshi,vikram.joshi@email.com,Indore,Madhya Pradesh,2025-01-29T00:00:00.000Z,2025-01-29T00:00:00.000Z,2025-02-07T00:00:00.000Z,2026-08-06T09:59:47.394Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/7ec5ceeb-6a38-491b-8231-055cc97e3f60/part-00000-359a242b-20cc-412e-b016-3eb8414c4741.c000.zstd.parquet,catalog_project1.source1.customers_raw,1786010386552,ffc0eeb8-d238-433c-8030-4735daf88af8
1007,Karan Mehta,karan.mehta@email.com,Pune,Maharashtra,2025-01-24T00:00:00.000Z,2025-01-24T00:00:00.000Z,2025-02-07T00:00:00.000Z,2026-08-06T09:59:47.394Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/7ec5ceeb-6a38-491b-8231-055cc97e3f60/part-00000-359a242b-20cc-412e-b016-3eb8414c4741.c000.zstd.parquet,catalog_project1.source1.customers_raw,1786010386552,ffc0eeb8-d238-433c-8030-4735daf88af8
1008,Anjali Singh,anjali.singh@email.com,Lucknow,Uttar Pradesh,2025-01-27T00:00:00.000Z,2025-01-27T00:00:00.000Z,2025-02-07T00:00:00.000Z,2026-08-06T09:59:47.394Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/7ec5ceeb-6a38-491b-8231-055cc97e3f60/part-00000-359a242b-20cc-412e-b016-3eb8414c4741.c000.zstd.parquet,catalog_project1.source1.customers_raw,1786010386552,ffc0eeb8-d238-433c-8030-4735daf88af8
1006,Neha Sharma,neha.sharma@email.com,Jaipur,Rajasthan,2025-01-22T00:00:00.000Z,2025-01-22T00:00:00.000Z,2025-02-07T00:00:00.000Z,2026-08-06T09:59:47.394Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/7ec5ceeb-6a38-491b-8231-055cc97e3f60/part-00000-359a242b-20cc-412e-b016-3eb8414c4741.c000.zstd.parquet,catalog_project1.source1.customers_raw,1786010386552,ffc0eeb8-d238-433c-8030-4735daf88af8
1004,Sneha Iyer,sneha.iyer@email.com,Bengaluru,Karnataka,2025-01-18T00:00:00.000Z,2025-01-18T00:00:00.000Z,2025-02-07T00:00:00.000Z,2026-08-06T09:59:47.394Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/7ec5ceeb-6a38-491b-8231-055cc97e3f60/part-00000-359a242b-20cc-412e-b016-3eb8414c4741.c000.zstd.parquet,catalog_project1.source1.customers_raw,1786010386552,ffc0eeb8-d238-433c-8030-4735daf88af8
1003,Amit Verma,amit.verma@email.com,Delhi,Delhi,2025-01-15T00:00:00.000Z,2025-01-15T00:00:00.000Z,2025-02-07T00:00:00.000Z,2026-08-06T09:59:47.394Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/7ec5ceeb-6a38-491b-8231-055cc97e3f60/part-00000-359a242b-20cc-412e-b016-3eb8414c4741.c000.zstd.parquet,catalog_project1.source1.customers_raw,1786010386552,ffc0eeb8-d238-433c-8030-4735daf88af8
1002,Priya Patel,priya.patel@email.com,Surat,Gujarat,2025-01-12T00:00:00.000Z,2025-01-12T00:00:00.000Z,2025-02-07T00:00:00.000Z,2026-08-06T09:59:47.394Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/7ec5ceeb-6a38-491b-8231-055cc97e3f60/part-00000-359a242b-20cc-412e-b016-3eb8414c4741.c000.zstd.parquet,catalog_project1.source1.customers_raw,1786010386552,ffc0eeb8-d238-433c-8030-4735daf88af8
1001,Rahul Shah,rahul.shah@email.com,Ahmedabad,Gujarat,2025-01-10T00:00:00.000Z,2025-01-10T00:00:00.000Z,2025-02-07T00:00:00.000Z,2026-08-06T09:59:47.394Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/7ec5ceeb-6a38-491b-8231-055cc97e3f60/part-00000-359a242b-20cc-412e-b016-3eb8414c4741.c000.zstd.parquet,catalog_project1.source1.customers_raw,1786010386552,ffc0eeb8-d238-433c-8030-4735daf88af8
1014,Krishna S,k.s@email.com,ValsadValsad,Gujarat,2025-02-12T00:00:00.000Z,2025-02-12T00:00:00.000Z,2025-02-13T00:00:00.000Z,2026-08-06T13:59:22.465Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/7ec5ceeb-6a38-491b-8231-055cc97e3f60/part-00000-2916745f-f07d-4fb1-a71e-3ff293eea122.c000.zstd.parquet,catalog_project1.source1.customers_raw,1786024761650,09788b3e-4e9d-437b-89c3-7a9491598156
1015,Krishna krishna patel,krishna.krishnapatel@email.com,Valsad,Gujarat,2025-02-13T00:00:00.000Z,2025-02-13T00:00:00.000Z,2025-02-13T00:00:00.000Z,2026-08-06T13:59:22.465Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/7ec5ceeb-6a38-491b-8231-055cc97e3f60/part-00001-1e55f47f-c4d1-4be6-94f7-289006f4fcc4.c000.zstd.parquet,catalog_project1.source1.customers_raw,1786024761650,09788b3e-4e9d-437b-89c3-7a9491598156
1010,Meera Nair,meera.nair@email.com,Kollam,Kerala,2025-02-01T00:00:00.000Z,2025-02-01T00:00:00.000Z,2025-02-10T00:00:00.000Z,2026-08-06T11:46:59.955Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/7ec5ceeb-6a38-491b-8231-055cc97e3f60/part-00000-8ac54404-10af-46b8-bbaf-3bcb15b3557b.c000.zstd.parquet,catalog_project1.source1.customers_raw,1786016818715,f8697191-260e-4927-adbb-7fd1e399c2f9
1012,Krishna S Patel,krishna.s.patel@email.com,Valsad,Gujarat,2025-02-10T00:00:00.000Z,2025-02-10T00:00:00.000Z,2025-02-10T00:00:00.000Z,2026-08-06T11:46:59.955Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/7ec5ceeb-6a38-491b-8231-055cc97e3f60/part-00001-c6d5e9b6-8458-4c62-b51a-b293a6245137.c000.zstd.parquet,catalog_project1.source1.customers_raw,1786016818715,f8697191-260e-4927-adbb-7fd1e399c2f9
1010,Meera Nair,meera.nair@email.com,Kannur,Kerala,2025-02-01T00:00:00.000Z,2025-02-01T00:00:00.000Z,2025-02-09T00:00:00.000Z,2026-08-06T10:08:35.451Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/7ec5ceeb-6a38-491b-8231-055cc97e3f60/part-00000-92666d69-6fe4-4239-ac67-c21fe6b9c5dc.c000.zstd.parquet,catalog_project1.source1.customers_raw,1786010914683,204933bf-d9e8-497c-88d2-fcb00e71e443
1011,Krishna Patel,krishna.patel@email.com,Valsad,Gujarat,2025-02-09T00:00:00.000Z,2025-02-09T00:00:00.000Z,2025-02-09T00:00:00.000Z,2026-08-06T10:08:35.451Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/7ec5ceeb-6a38-491b-8231-055cc97e3f60/part-00000-92666d69-6fe4-4239-ac67-c21fe6b9c5dc.c000.zstd.parquet,catalog_project1.source1.customers_raw,1786010914683,204933bf-d9e8-497c-88d2-fcb00e71e443
1010,Meera Nair,meera.nair@email.com,Kozhikode,Kerala,2025-02-01T00:00:00.000Z,2025-02-01T00:00:00.000Z,2025-02-11T00:00:00.000Z,2026-08-06T13:18:01.950Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/7ec5ceeb-6a38-491b-8231-055cc97e3f60/part-00000-5e467e62-f66d-46ad-b16b-019b3749ce71.c000.zstd.parquet,catalog_project1.source1.customers_raw,1786022280853,21f74b2c-01f1-41d3-8b26-c886c2b21114
1013,Krishna,krishna@email.com,Valsad,Gujarat,2025-02-11T00:00:00.000Z,2025-02-11T00:00:00.000Z,2025-02-11T00:00:00.000Z,2026-08-06T13:18:01.950Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/7ec5ceeb-6a38-491b-8231-055cc97e3f60/part-00001-d7dc7b7c-48d8-4564-b625-0f78fed7decf.c000.zstd.parquet,catalog_project1.source1.customers_raw,1786022280853,21f74b2c-01f1-41d3-8b26-c886c2b21114
1010,Meera Nair,meera.nair@email.com,Thiruvananthapuram,Kerala,2025-02-01T00:00:00.000Z,2025-02-01T00:00:00.000Z,2025-02-12T00:00:00.000Z,2026-08-06T13:37:24.271Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/7ec5ceeb-6a38-491b-8231-055cc97e3f60/part-00000-cd1f702f-708a-4891-997f-c8817a7036dd.c000.zstd.parquet,catalog_project1.source1.customers_raw,1786023443638,4ba7aaf1-f548-44ab-a0f8-cca6c14866ef
1014,K,k@email.com,Valsad,Gujarat,2025-02-12T00:00:00.000Z,2025-02-12T00:00:00.000Z,2025-02-12T00:00:00.000Z,2026-08-06T13:37:24.271Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/7ec5ceeb-6a38-491b-8231-055cc97e3f60/part-00001-fea68465-010c-40c0-abcf-59c9547bb912.c000.zstd.parquet,catalog_project1.source1.customers_raw,1786023443638,4ba7aaf1-f548-44ab-a0f8-cca6c14866ef
1014,Krishna Sumanbhai Patel,krishnasumanbhaipatel@email.com,Valsad City,Gujarat,2025-02-12T00:00:00.000Z,2025-02-12T00:00:00.000Z,2025-02-16T00:00:00.000Z,2026-08-07T07:39:53.812Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/7ec5ceeb-6a38-491b-8231-055cc97e3f60/part-00000-86a182d2-1d9e-46b7-ab74-ed9527b9ce13.c000.zstd.parquet,catalog_project1.source1.customers_raw,1786088391674,fae4517c-4a22-4100-be86-e82505fac6d9
1014,Krishna S S Patel,k.ss.patel@email.com,ValsadValsadValValsad,Gujarat,2025-02-12T00:00:00.000Z,2025-02-12T00:00:00.000Z,2025-02-15T00:00:00.000Z,2026-08-07T06:39:57.101Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/7ec5ceeb-6a38-491b-8231-055cc97e3f60/part-00000-6f0c9800-3964-478e-91cd-b9790d7fd365.c000.zstd.parquet,catalog_project1.source1.customers_raw,1786084795493,36eac210-12ea-4bec-9a2d-bc9c966c882c
1005,Rohan Gupta,rohan.gupta@email.com,Mumbai,Maharashtra,2025-01-20T00:00:00.000Z,2025-01-20T00:00:00.000Z,2025-02-08T00:00:00.000Z,2026-08-06T10:03:42.912Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/7ec5ceeb-6a38-491b-8231-055cc97e3f60/part-00000-7aa7a098-fed9-4794-88e1-cd7f5aaa565c.c000.zstd.parquet,catalog_project1.source1.customers_raw,1786010622275,125928f2-2b86-4017-9b55-7c146f44c3b1
1014,Krishna S S,k.ss@email.com,ValsadValValsad,Gujarat,2025-02-12T00:00:00.000Z,2025-02-12T00:00:00.000Z,2025-02-14T00:00:00.000Z,2026-08-06T14:08:55.818Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/7ec5ceeb-6a38-491b-8231-055cc97e3f60/part-00000-daa1b24b-6f69-4e62-80a3-0cc6231eed32.c000.zstd.parquet,catalog_project1.source1.customers_raw,1786025335182,78c01be5-ba63-451b-84a8-f27adb10be04

order_id,customer_id,order_date,status,created_date,modified_date,_ingestion_timestamp,_source_file,_source_table,_ingestion_job_id,_ingestion_pipeline_id
20001,1001,2025-03-01T00:00:00.000Z,Delivered,2025-03-01T00:00:00.000Z,2025-03-01T00:00:00.000Z,2026-07-24T09:25:01.428Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/b38c5b98-0317-49e0-ade0-50b4b3eb6c74/part-00000-7771e0f6-ed60-4c21-801e-604225fb98db.c000.zstd.parquet,catalog_project1.source1.orders_raw,1784885100612,7954ace6-65af-49a8-8ca6-186d9ce49efb
20002,1002,2025-03-01T00:00:00.000Z,Delivered,2025-03-01T00:00:00.000Z,2025-03-04T00:00:00.000Z,2026-07-24T09:25:01.428Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/b38c5b98-0317-49e0-ade0-50b4b3eb6c74/part-00000-7771e0f6-ed60-4c21-801e-604225fb98db.c000.zstd.parquet,catalog_project1.source1.orders_raw,1784885100612,7954ace6-65af-49a8-8ca6-186d9ce49efb
20003,1003,2025-03-02T00:00:00.000Z,Delivered,2025-03-02T00:00:00.000Z,2025-03-07T00:00:00.000Z,2026-07-24T09:25:01.428Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/b38c5b98-0317-49e0-ade0-50b4b3eb6c74/part-00000-7771e0f6-ed60-4c21-801e-604225fb98db.c000.zstd.parquet,catalog_project1.source1.orders_raw,1784885100612,7954ace6-65af-49a8-8ca6-186d9ce49efb
20004,1004,2025-03-02T00:00:00.000Z,Cancelled,2025-03-02T00:00:00.000Z,2025-03-10T00:00:00.000Z,2026-07-24T09:25:01.428Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/b38c5b98-0317-49e0-ade0-50b4b3eb6c74/part-00000-7771e0f6-ed60-4c21-801e-604225fb98db.c000.zstd.parquet,catalog_project1.source1.orders_raw,1784885100612,7954ace6-65af-49a8-8ca6-186d9ce49efb
20005,1005,2025-03-03T00:00:00.000Z,Delivered,2025-03-03T00:00:00.000Z,2025-03-13T00:00:00.000Z,2026-07-24T09:25:01.428Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/b38c5b98-0317-49e0-ade0-50b4b3eb6c74/part-00000-7771e0f6-ed60-4c21-801e-604225fb98db.c000.zstd.parquet,catalog_project1.source1.orders_raw,1784885100612,7954ace6-65af-49a8-8ca6-186d9ce49efb
20006,1006,2025-03-03T00:00:00.000Z,Shipped,2025-03-03T00:00:00.000Z,2025-03-16T00:00:00.000Z,2026-07-24T09:25:01.428Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/b38c5b98-0317-49e0-ade0-50b4b3eb6c74/part-00000-7771e0f6-ed60-4c21-801e-604225fb98db.c000.zstd.parquet,catalog_project1.source1.orders_raw,1784885100612,7954ace6-65af-49a8-8ca6-186d9ce49efb
20007,1007,2025-03-04T00:00:00.000Z,Delivered,2025-03-04T00:00:00.000Z,2025-03-19T00:00:00.000Z,2026-07-24T09:25:01.428Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/b38c5b98-0317-49e0-ade0-50b4b3eb6c74/part-00000-7771e0f6-ed60-4c21-801e-604225fb98db.c000.zstd.parquet,catalog_project1.source1.orders_raw,1784885100612,7954ace6-65af-49a8-8ca6-186d9ce49efb
20008,1008,2025-03-04T00:00:00.000Z,Pending,2025-03-04T00:00:00.000Z,2025-03-22T00:00:00.000Z,2026-07-24T09:25:01.428Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/b38c5b98-0317-49e0-ade0-50b4b3eb6c74/part-00000-7771e0f6-ed60-4c21-801e-604225fb98db.c000.zstd.parquet,catalog_project1.source1.orders_raw,1784885100612,7954ace6-65af-49a8-8ca6-186d9ce49efb
20009,1009,2025-03-05T00:00:00.000Z,Delivered,2025-03-05T00:00:00.000Z,2025-03-25T00:00:00.000Z,2026-07-24T09:25:01.428Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/b38c5b98-0317-49e0-ade0-50b4b3eb6c74/part-00000-7771e0f6-ed60-4c21-801e-604225fb98db.c000.zstd.parquet,catalog_project1.source1.orders_raw,1784885100612,7954ace6-65af-49a8-8ca6-186d9ce49efb
20010,1010,2025-03-05T00:00:00.000Z,Delivered,2025-03-05T00:00:00.000Z,2025-03-28T00:00:00.000Z,2026-07-24T09:25:01.428Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/b38c5b98-0317-49e0-ade0-50b4b3eb6c74/part-00000-7771e0f6-ed60-4c21-801e-604225fb98db.c000.zstd.parquet,catalog_project1.source1.orders_raw,1784885100612,7954ace6-65af-49a8-8ca6-186d9ce49efb

order_item_id,order_id,product_id,quantity,unit_price,created_date,modified_date,_ingestion_timestamp,_source_file,_source_table,_ingestion_job_id,_ingestion_pipeline_id
30001,20001,501,1,85000,2025-03-01T00:00:00.000Z,2025-03-01T00:00:00.000Z,2026-07-24T09:25:23.626Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/d1a6351d-054a-455a-84da-a312d4aacf6f/part-00000-38295c13-7f6a-4639-a945-13ce67c21495.c000.zstd.parquet,catalog_project1.source1.order_items_raw,1784885122917,d9b3c48b-771d-4f46-8ab1-7774c6858a14
30002,20001,502,1,2500,2025-03-02T00:00:00.000Z,2025-03-02T00:00:00.000Z,2026-07-24T09:25:23.626Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/d1a6351d-054a-455a-84da-a312d4aacf6f/part-00000-38295c13-7f6a-4639-a945-13ce67c21495.c000.zstd.parquet,catalog_project1.source1.order_items_raw,1784885122917,d9b3c48b-771d-4f46-8ab1-7774c6858a14
30003,20002,503,1,6500,2025-03-03T00:00:00.000Z,2025-03-03T00:00:00.000Z,2026-07-24T09:25:23.626Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/d1a6351d-054a-455a-84da-a312d4aacf6f/part-00000-38295c13-7f6a-4639-a945-13ce67c21495.c000.zstd.parquet,catalog_project1.source1.order_items_raw,1784885122917,d9b3c48b-771d-4f46-8ab1-7774c6858a14
30004,20003,504,1,12000,2025-03-04T00:00:00.000Z,2025-03-04T00:00:00.000Z,2026-07-24T09:25:23.626Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/d1a6351d-054a-455a-84da-a312d4aacf6f/part-00000-38295c13-7f6a-4639-a945-13ce67c21495.c000.zstd.parquet,catalog_project1.source1.order_items_raw,1784885122917,d9b3c48b-771d-4f46-8ab1-7774c6858a14
30005,20003,506,2,500,2025-03-05T00:00:00.000Z,2025-03-05T00:00:00.000Z,2026-07-24T09:25:23.626Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/d1a6351d-054a-455a-84da-a312d4aacf6f/part-00000-38295c13-7f6a-4639-a945-13ce67c21495.c000.zstd.parquet,catalog_project1.source1.order_items_raw,1784885122917,d9b3c48b-771d-4f46-8ab1-7774c6858a14
30006,20005,510,1,22000,2025-03-01T00:00:00.000Z,2025-03-01T00:00:00.000Z,2026-07-24T09:25:23.626Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/d1a6351d-054a-455a-84da-a312d4aacf6f/part-00000-38295c13-7f6a-4639-a945-13ce67c21495.c000.zstd.parquet,catalog_project1.source1.order_items_raw,1784885122917,d9b3c48b-771d-4f46-8ab1-7774c6858a14
30007,20006,507,2,3500,2025-03-02T00:00:00.000Z,2025-03-02T00:00:00.000Z,2026-07-24T09:25:23.626Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/d1a6351d-054a-455a-84da-a312d4aacf6f/part-00000-38295c13-7f6a-4639-a945-13ce67c21495.c000.zstd.parquet,catalog_project1.source1.order_items_raw,1784885122917,d9b3c48b-771d-4f46-8ab1-7774c6858a14
30008,20007,505,1,15000,2025-03-03T00:00:00.000Z,2025-03-03T00:00:00.000Z,2026-07-24T09:25:23.626Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/d1a6351d-054a-455a-84da-a312d4aacf6f/part-00000-38295c13-7f6a-4639-a945-13ce67c21495.c000.zstd.parquet,catalog_project1.source1.order_items_raw,1784885122917,d9b3c48b-771d-4f46-8ab1-7774c6858a14
30009,20009,509,2,2200,2025-03-04T00:00:00.000Z,2025-03-04T00:00:00.000Z,2026-07-24T09:25:23.626Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/d1a6351d-054a-455a-84da-a312d4aacf6f/part-00000-38295c13-7f6a-4639-a945-13ce67c21495.c000.zstd.parquet,catalog_project1.source1.order_items_raw,1784885122917,d9b3c48b-771d-4f46-8ab1-7774c6858a14
30010,20010,508,1,5500,2025-03-05T00:00:00.000Z,2025-03-05T00:00:00.000Z,2026-07-24T09:25:23.626Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/d1a6351d-054a-455a-84da-a312d4aacf6f/part-00000-38295c13-7f6a-4639-a945-13ce67c21495.c000.zstd.parquet,catalog_project1.source1.order_items_raw,1784885122917,d9b3c48b-771d-4f46-8ab1-7774c6858a14

product_id,product_name,category,brand,price,created_date,modified_date,_ingestion_timestamp,_source_file,_source_table,_ingestion_job_id,_ingestion_pipeline_id
501,Laptop Pro 14,Electronics,Dell,85000,2024-11-01T00:00:00.000Z,2024-11-05T00:00:00.000Z,2026-07-24T09:24:54.075Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/8c569cad-0602-43f2-bec0-fb2781ef81a8/part-00000-c59b7f8d-f881-49d8-88d7-1a8c233bfc97.c000.zstd.parquet,catalog_project1.source1.products_raw,1784885093399,2ae71454-dcb9-4d35-9c03-dc57febff9ca
502,Gaming Mouse,Electronics,Logitech,2500,2024-11-03T00:00:00.000Z,2024-11-10T00:00:00.000Z,2026-07-24T09:24:54.075Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/8c569cad-0602-43f2-bec0-fb2781ef81a8/part-00000-c59b7f8d-f881-49d8-88d7-1a8c233bfc97.c000.zstd.parquet,catalog_project1.source1.products_raw,1784885093399,2ae71454-dcb9-4d35-9c03-dc57febff9ca
503,Mechanical Keyboard,Electronics,Keychron,6500,2024-11-05T00:00:00.000Z,2024-11-15T00:00:00.000Z,2026-07-24T09:24:54.075Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/8c569cad-0602-43f2-bec0-fb2781ef81a8/part-00000-c59b7f8d-f881-49d8-88d7-1a8c233bfc97.c000.zstd.parquet,catalog_project1.source1.products_raw,1784885093399,2ae71454-dcb9-4d35-9c03-dc57febff9ca
504,Office Chair,Furniture,GreenSoul,12000,2024-11-07T00:00:00.000Z,2024-11-20T00:00:00.000Z,2026-07-24T09:24:54.075Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/8c569cad-0602-43f2-bec0-fb2781ef81a8/part-00000-c59b7f8d-f881-49d8-88d7-1a8c233bfc97.c000.zstd.parquet,catalog_project1.source1.products_raw,1784885093399,2ae71454-dcb9-4d35-9c03-dc57febff9ca
505,Study Table,Furniture,IKEA,15000,2024-11-09T00:00:00.000Z,2024-11-25T00:00:00.000Z,2026-07-24T09:24:54.075Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/8c569cad-0602-43f2-bec0-fb2781ef81a8/part-00000-c59b7f8d-f881-49d8-88d7-1a8c233bfc97.c000.zstd.parquet,catalog_project1.source1.products_raw,1784885093399,2ae71454-dcb9-4d35-9c03-dc57febff9ca
506,Water Bottle,Lifestyle,Milton,500,2024-11-11T00:00:00.000Z,2024-11-18T00:00:00.000Z,2026-07-24T09:24:54.075Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/8c569cad-0602-43f2-bec0-fb2781ef81a8/part-00000-c59b7f8d-f881-49d8-88d7-1a8c233bfc97.c000.zstd.parquet,catalog_project1.source1.products_raw,1784885093399,2ae71454-dcb9-4d35-9c03-dc57febff9ca
507,Wireless Earbuds,Electronics,Boat,3500,2024-11-13T00:00:00.000Z,2024-11-22T00:00:00.000Z,2026-07-24T09:24:54.075Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/8c569cad-0602-43f2-bec0-fb2781ef81a8/part-00000-c59b7f8d-f881-49d8-88d7-1a8c233bfc97.c000.zstd.parquet,catalog_project1.source1.products_raw,1784885093399,2ae71454-dcb9-4d35-9c03-dc57febff9ca
508,Smart Watch,Electronics,Noise,5500,2024-11-15T00:00:00.000Z,2024-11-28T00:00:00.000Z,2026-07-24T09:24:54.075Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/8c569cad-0602-43f2-bec0-fb2781ef81a8/part-00000-c59b7f8d-f881-49d8-88d7-1a8c233bfc97.c000.zstd.parquet,catalog_project1.source1.products_raw,1784885093399,2ae71454-dcb9-4d35-9c03-dc57febff9ca
509,Backpack,Lifestyle,Skybags,2200,2024-11-17T00:00:00.000Z,2024-11-30T00:00:00.000Z,2026-07-24T09:24:54.075Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/8c569cad-0602-43f2-bec0-fb2781ef81a8/part-00000-c59b7f8d-f881-49d8-88d7-1a8c233bfc97.c000.zstd.parquet,catalog_project1.source1.products_raw,1784885093399,2ae71454-dcb9-4d35-9c03-dc57febff9ca
510,Monitor 27 Inch,Electronics,LG,22000,2024-11-19T00:00:00.000Z,2024-11-21T00:00:00.000Z,2026-07-24T09:24:54.075Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/8c569cad-0602-43f2-bec0-fb2781ef81a8/part-00000-c59b7f8d-f881-49d8-88d7-1a8c233bfc97.c000.zstd.parquet,catalog_project1.source1.products_raw,1784885093399,2ae71454-dcb9-4d35-9c03-dc57febff9ca
514,Everyday Backpack,Lifestyle,SkyHighbags,1499,2024-12-05T00:00:00.000Z,2024-12-05T00:00:00.000Z,2026-08-07T06:40:07.295Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/8c569cad-0602-43f2-bec0-fb2781ef81a8/part-00000-0b1b085b-56f5-468d-9c1d-805744c20e95.c000.zstd.parquet,catalog_project1.source1.products_raw,1786084806201,614bf818-f366-4ea0-8857-d77d7db2c369
515,High Quality Backpack,Lifestyle,SkyHighbags,1999,2024-12-05T00:00:00.000Z,2024-12-05T00:00:00.000Z,2026-08-07T06:40:07.295Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/8c569cad-0602-43f2-bec0-fb2781ef81a8/part-00001-3b6499a5-c2bf-4c24-9e5d-97c6b818a301.c000.zstd.parquet,catalog_project1.source1.products_raw,1786084806201,614bf818-f366-4ea0-8857-d77d7db2c369
513,Waterproof Backpack,Lifestyle,SkyHighbags,2300,2024-12-03T00:00:00.000Z,2024-12-04T00:00:00.000Z,2026-08-04T12:46:17.481Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/8c569cad-0602-43f2-bec0-fb2781ef81a8/part-00000-1d14485a-0611-4f38-bb6e-36c2060e20d8.c000.zstd.parquet,catalog_project1.source1.products_raw,1785847576505,76822c3d-a1bb-407e-9531-7714b40218bf
514,Everyday Backpack,Lifestyle,SkyHighbags,999,2024-12-04T00:00:00.000Z,2024-12-04T00:00:00.000Z,2026-08-04T12:46:17.481Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/8c569cad-0602-43f2-bec0-fb2781ef81a8/part-00001-bdee6b52-e73d-47d0-8d8a-a2b13dd5b2ce.c000.zstd.parquet,catalog_project1.source1.products_raw,1785847576505,76822c3d-a1bb-407e-9531-7714b40218bf
511,Monitor 32 Inch,Electronics,LG,45000,2024-12-01T00:00:00.000Z,2024-12-02T00:00:00.000Z,2026-08-04T09:07:48.251Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/8c569cad-0602-43f2-bec0-fb2781ef81a8/part-00000-c186229f-aad9-47bf-9482-afc25d03702c.c000.zstd.parquet,catalog_project1.source1.products_raw,1785834466801,2f68b495-c6b5-4795-8ac5-2fc22e8e98e4
512,Monitor 21 Inch,Electronics,LG,23000,2024-12-02T00:00:00.000Z,2024-12-02T00:00:00.000Z,2026-08-04T09:07:48.251Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/8c569cad-0602-43f2-bec0-fb2781ef81a8/part-00001-5812cdd0-e25f-4769-a444-a4ee80bdd717.c000.zstd.parquet,catalog_project1.source1.products_raw,1785834466801,2f68b495-c6b5-4795-8ac5-2fc22e8e98e4
510,Monitor 27 Inch,Electronics,LG,24000,2024-11-19T00:00:00.000Z,2024-12-01T00:00:00.000Z,2026-08-03T12:53:33.656Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/8c569cad-0602-43f2-bec0-fb2781ef81a8/part-00000-4bc283ab-c740-46c5-b317-121df493499f.c000.zstd.parquet,catalog_project1.source1.products_raw,1785761612321,88040eca-d5be-495e-9163-2e3081e8ad3f
511,Monitor 30 Inch,Electronics,LG,30000,2024-12-01T00:00:00.000Z,2024-12-01T00:00:00.000Z,2026-08-03T12:53:33.656Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/8c569cad-0602-43f2-bec0-fb2781ef81a8/part-00001-81350002-84c1-4da2-8b56-b16a408118dc.c000.zstd.parquet,catalog_project1.source1.products_raw,1785761612321,88040eca-d5be-495e-9163-2e3081e8ad3f
512,Monitor 23 Inch,Electronics,LG,25200,2024-12-02T00:00:00.000Z,2024-12-03T00:00:00.000Z,2026-08-04T09:33:21.580Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/8c569cad-0602-43f2-bec0-fb2781ef81a8/part-00000-413f6aaf-ec06-491a-8510-ced9b0e6214b.c000.zstd.parquet,catalog_project1.source1.products_raw,1785836000844,ad90f6db-4cdc-4b8d-9be4-17a5ee1d52ea
513,Backpack,Lifestyle,SkyHighbags,2199,2024-12-03T00:00:00.000Z,2024-12-03T00:00:00.000Z,2026-08-04T09:33:21.580Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/8c569cad-0602-43f2-bec0-fb2781ef81a8/part-00001-03604915-f854-46eb-b78f-6fcbdbf09750.c000.zstd.parquet,catalog_project1.source1.products_raw,1785836000844,ad90f6db-4cdc-4b8d-9be4-17a5ee1d52ea
514,Everyday Backpack,Lifestyle,SkyHighbags,99,2024-12-05T00:00:00.000Z,2024-12-07T00:00:00.000Z,2026-08-07T08:05:37.157Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/8c569cad-0602-43f2-bec0-fb2781ef81a8/part-00000-14d5aa8b-9d03-45d5-a87c-bc6463040704.c000.zstd.parquet,catalog_project1.source1.products_raw,1786089936448,ce501539-1d7c-444d-a551-5c5ba5892cde
514,Everyday Backpack,Lifestyle,SkyHighbags,1299,2024-12-05T00:00:00.000Z,2024-12-06T00:00:00.000Z,2026-08-07T07:51:47.070Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/8c569cad-0602-43f2-bec0-fb2781ef81a8/part-00000-fb6b5fbb-1831-44fa-9ec6-c0bf99b24346.c000.zstd.parquet,catalog_project1.source1.products_raw,1786089106274,09d5b17c-7a57-45ec-99eb-dba374ad04d1
514,Everyday Backpack,Lifestyle,SkyHighbags,0,2024-12-05T00:00:00.000Z,2024-12-09T00:00:00.000Z,2026-08-07T08:44:36.463Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/8c569cad-0602-43f2-bec0-fb2781ef81a8/part-00000-391e73c3-6c68-4396-ae75-c073ef05f5ce.c000.zstd.parquet,catalog_project1.source1.products_raw,1786092275817,dc66ea12-cfc6-4f54-8751-dc4f57911a3a
514,Everyday Backpack,Lifestyle,SkyHighbags,9,2024-12-05T00:00:00.000Z,2024-12-08T00:00:00.000Z,2026-08-07T08:24:49.169Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/8c569cad-0602-43f2-bec0-fb2781ef81a8/part-00000-583d0165-58e7-4954-839a-36893ea19a16.c000.zstd.parquet,catalog_project1.source1.products_raw,1786091088105,950eead5-07fc-4c13-8fb6-a45cacea734e
505,Study Table,Furniture,IKEA,14000,2024-11-09T00:00:00.000Z,2024-12-16T00:00:00.000Z,2026-08-11T12:11:58.024Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/8c569cad-0602-43f2-bec0-fb2781ef81a8/part-00000-5f9a4af9-7225-4cb7-885d-3f4144643ab1.c000.zstd.parquet,catalog_project1.source1.products_raw,1786450316636,4fbbbd6b-3992-4fbd-b0b6-e65a7bb92418
505,Study Table,Furniture,IKEA,15000,2024-11-09T00:00:00.000Z,2024-12-17T00:00:00.000Z,2026-08-11T12:27:49.396Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/8c569cad-0602-43f2-bec0-fb2781ef81a8/part-00000-3c1ddfdf-07f2-4e11-a7d0-ff9a8a2d174c.c000.zstd.parquet,catalog_project1.source1.products_raw,1786451268658,2aafb7aa-a7f6-4582-8072-1830a45f1529
505,Study Table,Furniture,IKEA,99,2024-11-09T00:00:00.000Z,2024-12-14T00:00:00.000Z,2026-08-10T06:19:14.151Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/8c569cad-0602-43f2-bec0-fb2781ef81a8/part-00000-0372e87f-89ab-4abe-87a5-7e7e1dfbe3c6.c000.zstd.parquet,catalog_project1.source1.products_raw,1786342753440,7c916fb0-f832-44da-b6c3-774ff574ad6a
505,Study Table,Furniture,IKEA,9999,2024-11-09T00:00:00.000Z,2024-12-11T00:00:00.000Z,2026-08-10T05:15:59.328Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/8c569cad-0602-43f2-bec0-fb2781ef81a8/part-00000-10f4be3d-92a2-4755-bc6c-20d97b979cd9.c000.zstd.parquet,catalog_project1.source1.products_raw,1786338957774,3bcc58b0-74d1-469c-967c-b1a9ebaa515d
505,Study Table,Furniture,IKEA,10000,2024-11-09T00:00:00.000Z,2024-12-10T00:00:00.000Z,2026-08-07T11:11:11.827Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/8c569cad-0602-43f2-bec0-fb2781ef81a8/part-00000-4b40e3a9-d59d-44cc-a5ac-a71f7b274402.c000.zstd.parquet,catalog_project1.source1.products_raw,1786101070438,37475eea-9051-4cb6-ac7e-530c81104ba7
505,Study Table,Furniture,IKEA,999,2024-11-09T00:00:00.000Z,2024-12-12T00:00:00.000Z,2026-08-10T05:29:44.462Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/8c569cad-0602-43f2-bec0-fb2781ef81a8/part-00000-48d54910-fbca-486b-9cd9-90444b2f2460.c000.zstd.parquet,catalog_project1.source1.products_raw,1786339783751,162fb497-727c-4aa0-a606-5aac43973a05
505,Study Table,Furniture,IKEA,9099,2024-11-09T00:00:00.000Z,2024-12-13T00:00:00.000Z,2026-08-10T05:34:40.687Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/8c569cad-0602-43f2-bec0-fb2781ef81a8/part-00000-67bd54e5-1796-4c73-a4ac-4dd3f8848960.c000.zstd.parquet,catalog_project1.source1.products_raw,1786340079635,29f7245d-5b53-4871-946c-78e772e52b3e
505,Study Table,Furniture,IKEA,9,2024-11-09T00:00:00.000Z,2024-12-15T00:00:00.000Z,2026-08-10T06:22:28.856Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/8c569cad-0602-43f2-bec0-fb2781ef81a8/part-00000-6f2b81ab-d0f9-4c8f-82f3-d4172be47d92.c000.zstd.parquet,catalog_project1.source1.products_raw,1786342948143,571f55e5-1036-4750-b627-6120f708df8e

inventory_id,product_id,warehouse,stock,last_updated,created_date,modified_date,_ingestion_timestamp,_source_file,_source_table,_ingestion_job_id,_ingestion_pipeline_id
1,501,Ahmedabad_WH,25,2025-03-01T00:00:00.000Z,2024-12-01T00:00:00.000Z,2025-03-01T00:00:00.000Z,2026-07-24T09:25:15.889Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/243d2fc4-ef75-4475-96ce-2c7807cabe56/part-00000-afd49ac9-7ff0-406a-9cf7-e6d38681155f.c000.zstd.parquet,catalog_project1.source1.inventory_raw,1784885115210,69d05c1b-07a1-4bbf-956a-5b6467761415
2,502,Mumbai_WH,100,2025-03-01T00:00:00.000Z,2024-12-03T00:00:00.000Z,2025-03-01T00:00:00.000Z,2026-07-24T09:25:15.889Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/243d2fc4-ef75-4475-96ce-2c7807cabe56/part-00000-afd49ac9-7ff0-406a-9cf7-e6d38681155f.c000.zstd.parquet,catalog_project1.source1.inventory_raw,1784885115210,69d05c1b-07a1-4bbf-956a-5b6467761415
3,503,Delhi_WH,80,2025-03-01T00:00:00.000Z,2024-12-05T00:00:00.000Z,2025-03-01T00:00:00.000Z,2026-07-24T09:25:15.889Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/243d2fc4-ef75-4475-96ce-2c7807cabe56/part-00000-afd49ac9-7ff0-406a-9cf7-e6d38681155f.c000.zstd.parquet,catalog_project1.source1.inventory_raw,1784885115210,69d05c1b-07a1-4bbf-956a-5b6467761415
4,504,Bengaluru_WH,20,2025-03-01T00:00:00.000Z,2024-12-10T00:00:00.000Z,2025-03-01T00:00:00.000Z,2026-07-24T09:25:15.889Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/243d2fc4-ef75-4475-96ce-2c7807cabe56/part-00000-afd49ac9-7ff0-406a-9cf7-e6d38681155f.c000.zstd.parquet,catalog_project1.source1.inventory_raw,1784885115210,69d05c1b-07a1-4bbf-956a-5b6467761415
5,505,Ahmedabad_WH,30,2025-03-01T00:00:00.000Z,2024-12-15T00:00:00.000Z,2025-03-01T00:00:00.000Z,2026-07-24T09:25:15.889Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/243d2fc4-ef75-4475-96ce-2c7807cabe56/part-00000-afd49ac9-7ff0-406a-9cf7-e6d38681155f.c000.zstd.parquet,catalog_project1.source1.inventory_raw,1784885115210,69d05c1b-07a1-4bbf-956a-5b6467761415
6,506,Mumbai_WH,500,2025-03-01T00:00:00.000Z,2024-12-18T00:00:00.000Z,2025-03-01T00:00:00.000Z,2026-07-24T09:25:15.889Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/243d2fc4-ef75-4475-96ce-2c7807cabe56/part-00000-afd49ac9-7ff0-406a-9cf7-e6d38681155f.c000.zstd.parquet,catalog_project1.source1.inventory_raw,1784885115210,69d05c1b-07a1-4bbf-956a-5b6467761415
7,507,Delhi_WH,120,2025-03-01T00:00:00.000Z,2024-12-20T00:00:00.000Z,2025-03-01T00:00:00.000Z,2026-07-24T09:25:15.889Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/243d2fc4-ef75-4475-96ce-2c7807cabe56/part-00000-afd49ac9-7ff0-406a-9cf7-e6d38681155f.c000.zstd.parquet,catalog_project1.source1.inventory_raw,1784885115210,69d05c1b-07a1-4bbf-956a-5b6467761415
8,508,Bengaluru_WH,70,2025-03-01T00:00:00.000Z,2024-12-25T00:00:00.000Z,2025-03-01T00:00:00.000Z,2026-07-24T09:25:15.889Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/243d2fc4-ef75-4475-96ce-2c7807cabe56/part-00000-afd49ac9-7ff0-406a-9cf7-e6d38681155f.c000.zstd.parquet,catalog_project1.source1.inventory_raw,1784885115210,69d05c1b-07a1-4bbf-956a-5b6467761415
9,509,Ahmedabad_WH,90,2025-03-01T00:00:00.000Z,2024-12-28T00:00:00.000Z,2025-03-01T00:00:00.000Z,2026-07-24T09:25:15.889Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/243d2fc4-ef75-4475-96ce-2c7807cabe56/part-00000-afd49ac9-7ff0-406a-9cf7-e6d38681155f.c000.zstd.parquet,catalog_project1.source1.inventory_raw,1784885115210,69d05c1b-07a1-4bbf-956a-5b6467761415
10,510,Mumbai_WH,40,2025-03-01T00:00:00.000Z,2024-12-30T00:00:00.000Z,2025-03-01T00:00:00.000Z,2026-07-24T09:25:15.889Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/243d2fc4-ef75-4475-96ce-2c7807cabe56/part-00000-afd49ac9-7ff0-406a-9cf7-e6d38681155f.c000.zstd.parquet,catalog_project1.source1.inventory_raw,1784885115210,69d05c1b-07a1-4bbf-956a-5b6467761415

payment_id,order_id,payment_method,payment_status,amount,created_date,modified_date,_ingestion_timestamp,_source_file,_source_table,_ingestion_job_id,_ingestion_pipeline_id
40001,20001,Credit Card,Success,87500,2025-03-01T00:00:00.000Z,2025-03-01T00:00:00.000Z,2026-07-24T09:25:08.252Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/d54b9efa-7202-4486-b33a-04e5d22af3d8/part-00000-97464975-4607-480c-a937-28c894cb5abc.c000.zstd.parquet,catalog_project1.source1.payments_raw,1784885107569,76704af5-2412-4434-960c-597923f5df73
40002,20002,UPI,Success,6500,2025-03-04T00:00:00.000Z,2025-03-04T00:00:00.000Z,2026-07-24T09:25:08.252Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/d54b9efa-7202-4486-b33a-04e5d22af3d8/part-00000-97464975-4607-480c-a937-28c894cb5abc.c000.zstd.parquet,catalog_project1.source1.payments_raw,1784885107569,76704af5-2412-4434-960c-597923f5df73
40003,20003,Net Banking,Success,13000,2025-03-07T00:00:00.000Z,2025-03-07T00:00:00.000Z,2026-07-24T09:25:08.252Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/d54b9efa-7202-4486-b33a-04e5d22af3d8/part-00000-97464975-4607-480c-a937-28c894cb5abc.c000.zstd.parquet,catalog_project1.source1.payments_raw,1784885107569,76704af5-2412-4434-960c-597923f5df73
40004,20004,UPI,Refunded,0,2025-03-10T00:00:00.000Z,2025-03-10T00:00:00.000Z,2026-07-24T09:25:08.252Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/d54b9efa-7202-4486-b33a-04e5d22af3d8/part-00000-97464975-4607-480c-a937-28c894cb5abc.c000.zstd.parquet,catalog_project1.source1.payments_raw,1784885107569,76704af5-2412-4434-960c-597923f5df73
40005,20005,Debit Card,Success,22000,2025-03-13T00:00:00.000Z,2025-03-13T00:00:00.000Z,2026-07-24T09:25:08.252Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/d54b9efa-7202-4486-b33a-04e5d22af3d8/part-00000-97464975-4607-480c-a937-28c894cb5abc.c000.zstd.parquet,catalog_project1.source1.payments_raw,1784885107569,76704af5-2412-4434-960c-597923f5df73
40006,20006,Credit Card,Pending,7000,2025-03-16T00:00:00.000Z,2025-03-16T00:00:00.000Z,2026-07-24T09:25:08.252Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/d54b9efa-7202-4486-b33a-04e5d22af3d8/part-00000-97464975-4607-480c-a937-28c894cb5abc.c000.zstd.parquet,catalog_project1.source1.payments_raw,1784885107569,76704af5-2412-4434-960c-597923f5df73
40007,20007,UPI,Success,15000,2025-03-19T00:00:00.000Z,2025-03-19T00:00:00.000Z,2026-07-24T09:25:08.252Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/d54b9efa-7202-4486-b33a-04e5d22af3d8/part-00000-97464975-4607-480c-a937-28c894cb5abc.c000.zstd.parquet,catalog_project1.source1.payments_raw,1784885107569,76704af5-2412-4434-960c-597923f5df73
40008,20008,Wallet,Pending,0,2025-03-22T00:00:00.000Z,2025-03-22T00:00:00.000Z,2026-07-24T09:25:08.252Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/d54b9efa-7202-4486-b33a-04e5d22af3d8/part-00000-97464975-4607-480c-a937-28c894cb5abc.c000.zstd.parquet,catalog_project1.source1.payments_raw,1784885107569,76704af5-2412-4434-960c-597923f5df73
40009,20009,Credit Card,Success,4400,2025-03-25T00:00:00.000Z,2025-03-25T00:00:00.000Z,2026-07-24T09:25:08.252Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/d54b9efa-7202-4486-b33a-04e5d22af3d8/part-00000-97464975-4607-480c-a937-28c894cb5abc.c000.zstd.parquet,catalog_project1.source1.payments_raw,1784885107569,76704af5-2412-4434-960c-597923f5df73
40010,20010,UPI,Success,5500,2025-03-28T00:00:00.000Z,2025-03-28T00:00:00.000Z,2026-07-24T09:25:08.252Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/d54b9efa-7202-4486-b33a-04e5d22af3d8/part-00000-97464975-4607-480c-a937-28c894cb5abc.c000.zstd.parquet,catalog_project1.source1.payments_raw,1784885107569,76704af5-2412-4434-960c-597923f5df73

supplier_id,supplier_name,contact_name,contact_email,country,city,created_date,modified_date,_ingestion_timestamp,_source_file,_source_table,_ingestion_job_id,_ingestion_pipeline_id
101,Tech Distributors,Amit Sharma,amit@techdist.com,India,Delhi,2024-11-01T00:00:00.000Z,2024-11-05T00:00:00.000Z,2026-08-12T12:31:43.605Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/2a1a11c2-7cb1-467c-9658-ddbfd8761927/part-00000-9152b3bc-17ef-4e1c-8cc2-11dfab41fb36.c000.zstd.parquet,catalog_project1.source1.suppliers_raw,1786537901678,f4f27b20-b04b-47d9-bca7-338fe34088a3
102,Global Supplies,Priya Singh,priya@globalsup.com,India,Mumbai,2024-11-03T00:00:00.000Z,2024-11-10T00:00:00.000Z,2026-08-12T12:31:43.605Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/2a1a11c2-7cb1-467c-9658-ddbfd8761927/part-00000-9152b3bc-17ef-4e1c-8cc2-11dfab41fb36.c000.zstd.parquet,catalog_project1.source1.suppliers_raw,1786537901678,f4f27b20-b04b-47d9-bca7-338fe34088a3
103,Furniture World,Ravi Kumar,ravi@furnworld.com,India,Bangalore,2024-11-05T00:00:00.000Z,2024-11-15T00:00:00.000Z,2026-08-12T12:31:43.605Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/2a1a11c2-7cb1-467c-9658-ddbfd8761927/part-00000-9152b3bc-17ef-4e1c-8cc2-11dfab41fb36.c000.zstd.parquet,catalog_project1.source1.suppliers_raw,1786537901678,f4f27b20-b04b-47d9-bca7-338fe34088a3
104,Lifestyle Traders,Neha Jain,neha@lifestyletraders.com,India,Chennai,2024-11-07T00:00:00.000Z,2024-11-20T00:00:00.000Z,2026-08-12T12:31:43.605Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/2a1a11c2-7cb1-467c-9658-ddbfd8761927/part-00000-9152b3bc-17ef-4e1c-8cc2-11dfab41fb36.c000.zstd.parquet,catalog_project1.source1.suppliers_raw,1786537901678,f4f27b20-b04b-47d9-bca7-338fe34088a3
105,ElectroMart,Suresh Patel,suresh@electromart.com,India,Ahmedabad,2024-11-09T00:00:00.000Z,2024-11-25T00:00:00.000Z,2026-08-12T12:31:43.605Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/2a1a11c2-7cb1-467c-9658-ddbfd8761927/part-00000-9152b3bc-17ef-4e1c-8cc2-11dfab41fb36.c000.zstd.parquet,catalog_project1.source1.suppliers_raw,1786537901678,f4f27b20-b04b-47d9-bca7-338fe34088a3
106,Urban Essentials,Anjali Mehta,anjali@urbaness.com,India,Pune,2024-11-11T00:00:00.000Z,2024-11-18T00:00:00.000Z,2026-08-12T12:31:43.605Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/2a1a11c2-7cb1-467c-9658-ddbfd8761927/part-00000-9152b3bc-17ef-4e1c-8cc2-11dfab41fb36.c000.zstd.parquet,catalog_project1.source1.suppliers_raw,1786537901678,f4f27b20-b04b-47d9-bca7-338fe34088a3
107,Gadget Hub,Vikram Rao,vikram@gadgethub.com,India,Hyderabad,2024-11-13T00:00:00.000Z,2024-11-22T00:00:00.000Z,2026-08-12T12:31:43.605Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/2a1a11c2-7cb1-467c-9658-ddbfd8761927/part-00000-9152b3bc-17ef-4e1c-8cc2-11dfab41fb36.c000.zstd.parquet,catalog_project1.source1.suppliers_raw,1786537901678,f4f27b20-b04b-47d9-bca7-338fe34088a3
108,Smart Solutions,Deepa Joshi,deepa@smartsol.com,India,Kolkata,2024-11-15T00:00:00.000Z,2024-11-28T00:00:00.000Z,2026-08-12T12:31:43.605Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/2a1a11c2-7cb1-467c-9658-ddbfd8761927/part-00000-9152b3bc-17ef-4e1c-8cc2-11dfab41fb36.c000.zstd.parquet,catalog_project1.source1.suppliers_raw,1786537901678,f4f27b20-b04b-47d9-bca7-338fe34088a3
109,Office Supplies Co,Manish Gupta,manish@officesupco.com,India,Jaipur,2024-11-17T00:00:00.000Z,2024-11-30T00:00:00.000Z,2026-08-12T12:31:43.605Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/2a1a11c2-7cb1-467c-9658-ddbfd8761927/part-00000-9152b3bc-17ef-4e1c-8cc2-11dfab41fb36.c000.zstd.parquet,catalog_project1.source1.suppliers_raw,1786537901678,f4f27b20-b04b-47d9-bca7-338fe34088a3
110,Home Needs,Sunita Rao,sunita@homeneeds.com,India,Lucknow,2024-11-19T00:00:00.000Z,2024-11-21T00:00:00.000Z,2026-08-12T12:31:43.605Z,s3://dbstorage-prod-sul6n/uc/1304586b-ace6-48cf-aa0c-9060a670d164/aaed439d-3e9e-4b40-8781-db3348b2e0d7/__unitystorage/catalogs/dd1feeea-2452-4691-8c0f-ca26a131ceb4/tables/2a1a11c2-7cb1-467c-9658-ddbfd8761927/part-00000-9152b3bc-17ef-4e1c-8cc2-11dfab41fb36.c000.zstd.parquet,catalog_project1.source1.suppliers_raw,1786537901678,f4f27b20-b04b-47d9-bca7-338fe34088a3

In [0]:
tables = [
    "catalog_project1.bronze.customers", 
    "catalog_project1.bronze.orders", 
    "catalog_project1.bronze.order_items", 
    "catalog_project1.bronze.products", 
    "catalog_project1.bronze.inventory", 
    "catalog_project1.bronze.payments" 
] 

for table in tables: 
    spark.sql(f"SELECT * FROM {table}").printSchema()

root
 |-- customer_id: integer (nullable = true)
 |-- name: string (nullable = true)
 |-- email: string (nullable = true)
 |-- city: string (nullable = true)
 |-- state: string (nullable = true)
 |-- signup_date: timestamp (nullable = true)
 |-- created_date: timestamp (nullable = true)
 |-- modified_date: timestamp (nullable = true)
 |-- _ingestion_timestamp: timestamp (nullable = true)
 |-- _source_file: string (nullable = true)
 |-- _source_table: string (nullable = true)
 |-- _ingestion_job_id: string (nullable = true)
 |-- _ingestion_pipeline_id: string (nullable = true)

root
 |-- order_id: integer (nullable = true)
 |-- customer_id: integer (nullable = true)
 |-- order_date: timestamp (nullable = true)
 |-- status: string (nullable = true)
 |-- created_date: timestamp (nullable = true)
 |-- modified_date: timestamp (nullable = true)
 |-- _ingestion_timestamp: timestamp (nullable = true)
 |-- _source_file: string (nullable = true)
 |-- _source_table: string (nullable = true)
 |-- _ingestion_job_id: string (nullable = true)
 |-- _ingestion_pipeline_id: string (nullable = true)

root
 |-- order_item_id: integer (nullable = true)
 |-- order_id: integer (nullable = true)
 |-- product_id: integer (nullable = true)
 |-- quantity: integer (nullable = true)
 |-- unit_price: integer (nullable = true)
 |-- created_date: timestamp (nullable = true)
 |-- modified_date: timestamp (nullable = true)
 |-- _ingestion_timestamp: timestamp (nullable = true)
 |-- _source_file: string (nullable = true)
 |-- _source_table: string (nullable = true)
 |-- _ingestion_job_id: string (nullable = true)
 |-- _ingestion_pipeline_id: string (nullable = true)

root
 |-- product_id: integer (nullable = true)
 |-- product_name: string (nullable = true)
 |-- category: string (nullable = true)
 |-- brand: string (nullable = true)
 |-- price: integer (nullable = true)
 |-- created_date: timestamp (nullable = true)
 |-- modified_date: timestamp (nullable = true)
 |-- _ingestion_timestamp: timestamp (nullable = true)
 |-- _source_file: string (nullable = true)
 |-- _source_table: string (nullable = true)
 |-- _ingestion_job_id: string (nullable = true)
 |-- _ingestion_pipeline_id: string (nullable = true)

root
 |-- inventory_id: integer (nullable = true)
 |-- product_id: integer (nullable = true)
 |-- warehouse: string (nullable = true)
 |-- stock: integer (nullable = true)
 |-- last_updated: timestamp (nullable = true)
 |-- created_date: timestamp (nullable = true)
 |-- modified_date: timestamp (nullable = true)
 |-- _ingestion_timestamp: timestamp (nullable = true)
 |-- _source_file: string (nullable = true)
 |-- _source_table: string (nullable = true)
 |-- _ingestion_job_id: string (nullable = true)
 |-- _ingestion_pipeline_id: string (nullable = true)

root
 |-- payment_id: integer (nullable = true)
 |-- order_id: integer (nullable = true)
 |-- payment_method: string (nullable = true)
 |-- payment_status: string (nullable = true)
 |-- amount: integer (nullable = true)
 |-- created_date: timestamp (nullable = true)
 |-- modified_date: timestamp (nullable = true)
 |-- _ingestion_timestamp: timestamp (nullable = true)
 |-- _source_file: string (nullable = true)
 |-- _source_table: string (nullable = true)
 |-- _ingestion_job_id: string (nullable = true)
 |-- _ingestion_pipeline_id: string (nullable = true)